// <auto-generated />
using System;
using CarsIsland.Catalog.Infrastructure.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarsIsland.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CarCatalogDbContext))]
    partial class CarCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarsIsland.Catalog.Domain.Model.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("AvailableForRent")
                        .HasColumnType("bit");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerDay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2605c956-1ab4-4ce9-ad90-559978d754dd"),
                            AvailableForRent = true,
                            Brand = "BMW",
                            Model = "320",
                            PricePerDay = 200m
                        },
                        new
                        {
                            Id = new Guid("8907d3d0-d16f-49e1-8ae6-570cd3d20c84"),
                            AvailableForRent = true,
                            Brand = "Audi",
                            Model = "A1",
                            PricePerDay = 120m
                        },
                        new
                        {
                            Id = new Guid("9d121cd4-28a9-4ccf-94fd-d04041c81988"),
                            AvailableForRent = true,
                            Brand = "Mercedes",
                            Model = "E200",
                            PricePerDay = 250m
                        },
                        new
                        {
                            Id = new Guid("e0ea016f-9c7a-4bc9-86e1-8fdae0b334f0"),
                            AvailableForRent = true,
                            Brand = "Ford",
                            Model = "Focus",
                            PricePerDay = 90m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
